F1bonacc1/process-compose

- .gitignore
- README.md
- default.nix
- flake.lock
- flake.nix
I'm very impressed with the work so far on this repo :tada: ... so I decided to add Nix Flake support.
I think `process-compose` could be a missing link in the Nix ecosystem, since with the combination with projects like https://numtide.github.io/devshell/
the necessary binaries for the services can be provided consistently for awesome OCI-less developer environments.
> feat: add nix flake package manager support

- flake.nix
Yay, breaking changes on minor version updates!
Cause: https://github.com/NixOS/nix/issues/6448#issuecomment-1132855605
I'll try submitting this package to nixpkgs, so the maintanence of the build instructions can be done separately. Until then this makes trying out process-compose for the latest nix users a breeze.
> Make `nix run .` work on Nix 2.8+

- default.nix
- flake.lock
```
[kszabo@paks3:~/projects/process-compose]$ process-compose
process-compose: command not found
[kszabo@paks3:~/projects/process-compose]$ nix profile install .
[kszabo@paks3:~/projects/process-compose]$ process-compose 
completion  (Generate the autocompletion script for the specified shell)  help        (Help about any command)                                      process     (Execute operations on available processes)
[kszabo@paks3:~/projects/process-compose]$ process-compose process 
list     (List available processes)  restart  (Restart a process)         start    (Start a process)           stop     (Stop a running process)   
```
Also bumped the flake.lock file so the latest dependencies do not complain about Go <1.18
> Install shell completions automatically via Nix

- README.md
- default.nix
- flake.nix
now that this project is packaged in the [main nixpkgs repostitory](https://github.com/NixOS/nixpkgs/pull/201877)
the need for instructing people to compile from source is unnecessary.
I'm also proposing changes to include process-compose as a built-in component in this project:
https://devenv.sh/
https://github.com/cachix/devenv/issues/78
The above would solve problems like https://github.com/F1bonacc1/process-compose/issues/14
and provide nice common service descriptions for common architectural components (postgres/kafka/redis/etc.).
Might be worth mentioning in the README.md once the above issue is resolved.
> Rework nix instructions now that nixpkgs has it

- .goreleaser.yaml
- Makefile
- default.nix
- flake.lock
- flake.nix
- src/cmd/version.go
- src/config/config.go
Hi @thenonameguy 
I was trying to add a version info command that prints the following output:
```
Version:        v0.29.1
Commit:         00a3211
Date (UTC):     2022-12-24T21:19:13Z
```
I did some changes to `default.nix` and `flake.nix`, but it still doesn't work as expected:
```
Version:        v0.29.1
Commit:         dirty
Date (UTC):     20221224212048
```
Can you please give me a hint or send me to the documentation on how to do it properly?
Also, I made some changes to `default.nix` to make it more like: 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/process-compose/default.nix
Can you please confirm that it's indeed the right direction?
Thanks!
> Added version command - prints process-compose version and build info

- src/tui/log-viewer.go
This PR escapes the log line in the `useAnsi` branch of `LogView.WriteString`. Without this escape, substrings that match `[\w+]` are interpreted by regions and cause display issues.
> Escape the TUI log lines in ANSI color mode

- README.md
- src/app/process.go
- src/app/process_unix.go
- src/app/process_windows.go
- src/types/process.go
`shutdown.only_kill_process` defaults to false (backwards compatible). In this case and on UNIX platforms, the shutdown signal is sent to the running process' process group. If `shutdown.only_kill_process` is true, the shutdown signal is only sent to the running process itself.
Closes #67
> config: add process.shutdown.only_kill_process option

- README.md
- src/app/project_runner.go
- src/types/process.go
a bool flag, if set to true, shuts down all processes once
given process ends (regardless of exit code)
this can be used together with `availability.restart = on_failure` to
have the process restarted on failure and only exit PC on success
closes #77
> feat: availability.exit_on_end

- flake.nix
overlays should not be defined per-system (see: https://discourse.nixos.org/t/how-to-consume-a-eachdefaultsystem-flake-overlay/19420/3)
also, overlay (singular) is not an official output
so we keep overlays.default only
I'm working on a project which doesn't use flakes yet so prefer to consume
via an overlay :)
> bugfix: fix definition of flake overlays output

- flake.nix
- src/app/commander_interface.go
- src/app/process.go
- src/app/project_runner.go
- src/app/system_test.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/cmd/run.go
- src/cmd/up.go
- src/command/command.go
- src/command/command_wrapper.go
- src/loader/merger_test.go
- src/tui/proc-info-form.go
- src/types/process.go
- src/types/validators.go
`entrypoint` is an optional array of strings which can be set on the process config
to override default shell (and shellArg) used to run the `command`
When `entrypoint` is set and is non-empty, `command` can also be omitted.
This is useful if one want's to:
1. use a different shell per process
2. run any other executable directly, without a shell wrapper
Equivalent of [docker-compose run](https://docs.docker.com/engine/reference/commandline/compose_run/)
which can be used to run a chosen process in the foreground (with std(in|out|err) attached),
while it's dependencies are ran in the background (no logs printed to stdio).
Deps can be disabled via --no-deps flag.
Additional arguments can be passed to the process after `--` separator, for example:
```sh
process-compose run main -- arg1 arg2 …
```
> implement process entrypoint and run cmd

- .github/workflows/nix.yml
- default.nix
* Add basic nix build gha ci to ensure the process-compose package builds before new releases are tagged.
> imp: add nix ci gha job

- README.md
- www/docs/index.md
Found once in the docs and once in the README. It looks like the website is generated, happy to revert that part of the commit.
> README: fix typo

- src/tui/view.go
Currently, when you open the find Dialog, pressing escape to close it does not work. First.
First, i tried checking if a `DialogPage` existed, and if it does, close it. I added this in the `ActionLogFindExit`, but this closing of the dialog page is not always connected to `Esc` is the keybinding is changed. So it needed an extra check for that. This didn't feel right to me. 
Thinking about it, it felt odd the escape never reached the PageDialog even though that page has focus. It seems that's because all the keybindings are captures in the `appView`. This always goes first, before any active page. 
So I moved this mapping to the `mainGrid` page. This caused Control+C to not be captures. So i moved just this keybinding so the appView. 
This allows the PageDialog to handle Escape before …
> move setInputCapture to mainGrid, except ctrl+c

- src/tui/proc-filter.go
- src/tui/proc-table.go
- src/tui/view.go
Add the ability to filter on process list using `/` (vim keybinding). 
Can be confirmed with enter (has the same issue as https://github.com/F1bonacc1/process-compose/pull/135)
Or cancelled with Escape. On start it resets the search, and searches as you type to see the result. 
If cancelled early it will reset the search. 
https://github.com/F1bonacc1/process-compose/assets/126677968/83be52e7-7a94-4bd8-ab8d-5866c2f566f7
I did run into one issue where, if the search results in an empty list, it hangs the process. The processes are still running in the background (seen by the logs updating). But the TUI doesn't respond anymore, i haven't been able to figure out what the reasoning is behind this. If i click escape quickly (to cancel the search), the problem doesn't show up.
> Feature: Filter on process list

- fixtures-code/process-compose-shutdown-inorder.yaml
- src/app/project_opts.go
- src/app/project_runner.go
- src/app/system_test.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/config/Flags.go
processes that depend on others to start may also need to finish before them and perform some cleanup. This change makes sure that's the case.
fixes #145
> feat: shutdown in reverse dependency order

- src/app/process.go
- src/app/project_runner.go
I noticed that, in my use case (`A(depends_on: B started) -> B(depends_on: C healthy) -> C`):
- B successfully waits for C to be healthy
- A starts at the same time as C, when it should start after B
this change fixes the problematic behavior above.
> fix: wait for processes to start when `condition: process_started`

- src/cmd/attach.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/config/Flags.go
- src/tui/proc-table.go
This commit changes the --ref-rate/-r flag so that it accepts both an
integer in seconds (original behavior) and a custom duration string (new
behavior). This lets the user draw the UI at a higher refresh rate such
as 30fps.
It also makes a minor change in src/tui/proc-table.go, changing from
using `time.After` to `time.Ticker` to make the code slightly more
performant.
> Allow specifying duration for --ref-rate/-r flag

- src/api/server.go
- src/app/project_runner.go
- src/app/system_test.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/cmd/run.go
- src/cmd/up.go
To prevent a race condition seen in https://github.com/F1bonacc1/process-compose/issues/197:
1. On the client:
a. User runs `process-compose down`
b. Client makes request to `/project/stop`
2. On the server:
a. `ProjectRunner.ShutDownProject()` stops all processes
b. `cmd.runProject()` stops blocking
c. Exits before `PcApi.ShutDownProject` has written the response
3. On the client:
a. Gets `EOF` reading the response because the server has gone away
I can't think of a way to reproduce this in a test, except for something
convoluted like creating a custom client that introduces a delay in
reading the response.
It can be "manually" simulated by adding a small delay here though:
```patch
diff --git a/src/api/pc_api.go b/src/api/pc_api.go
index d123257..d069399 100644
--- a/src/api/pc_api.go …
```
> [Fixes #197] Gracefully shutdown HTTP server

- src/client/logs.go
Currently the write error message emitted by `process-compose process logs --tail` is indistinguishable from actual log output coming from the process.
```yaml
processes:
never_exit:
command: sleep infinity
foo:
command: |
echo 1
echo 2
echo 3
```
will log as:
```
$ process-compose process logs -u test.sock -n 2 foo 2>/dev/null
2
3
write close: write unix ->test.sock: write: broken pipe
```
This change will make it so that `write close: write unix ->test.sock: write: broken pipe` would be printed to stderr, i.e. the same command as above would log as:
```
$ process-compose process logs -u test.sock -n 2 foo 2>/dev/null
2
3
```
> Print log write errors to stderr rather than stdout

- src/api/server.go
Currently, if two instances of process-compose are started with the same unix socket, the first instance is orphaned without any way to shut it down:
```
> process-compose up -u /tmp/sock --tui=false >/dev/null 2>&1 &
[1] 52138
> process-compose up -u /tmp/sock --tui=false >/dev/null 2>&1 &
[2] 52217
> process-compose down -u /tmp/sock
[2]  + done       process-compose up -u /tmp/sock --tui=false > /dev/null 2>&1
> process-compose down -u /tmp/sock
24-08-07 11:59:19.436 FTL failed to stop project error="Post \"http://unix/project/stop/\": dial unix /tmp/sock: connect: no such file or directory"
> pgrep process-compose
52138
```
Instead of unconditionally removing an existing unix socket, error if it is already in use.
> fix: check if unix socket is in use

- src/app/project_runner.go
- src/types/process.go
- www/docs/launcher.md
resolves #225 
Here’s a simple process-compose configuration to try this feature:
```yaml
processes:
process1:
command: "echo 'Hi from Process1'"
depends_on:
process2:
condition: process_completed_successfully
availability:
exit_on_skipped: true
process2:
command: "echo 'Hi from Process2'; exit 1"
process3:
command: "while true; do echo 'Running...'; sleep 1; done"
```
> feat: Add `availability.exit_on_skipped`

- src/command/stopper_unix.go
This protects us from a potential (but rare) race condition where
1. the process we are trying to signal terminates of its own accord
2. its PID gets reaped in the `os.Process.Wait` call
3. a new process with the same PID gets spawned
before our signal actually gets sent.
This is achieved by using the higher-level `os.Process` API directly, which
has some synchronization to prevent `os.Process.Wait` and `os.Process.Signal`
from racing.
> fix: Prefer os.Process.Signal to syscall.Kill

- src/tui/view.go
When the user closes their terminal (as opposed to ctrl-c), the terminal might close the tty without waiting for process-compose to exit. This causes `pcv.appView.Run` to return an error, which triggers a `log.Fatal`:
```
ERR Failed to start TUI error="read /dev/tty: input/output error"
```
This leads to a race where `log.Fatal` might call `os.Exit` before the project's processes can be stopped, leaving them orphaned.
Change `log.Fatal` to `log.Error` and explicitly shutdown the project to make sure processes aren't left behind.
> tui: don't log.Fatal on appView.Run error

- src/loader/loader.go
- src/loader/validators.go
Prints error and exits if undefined dependencies exist.
Fixes #261
> fix #261: validate all dependencies are defined

- default.nix
Regular builds already specify CGO_ENABLED=0, making nix binaries static as well.
Fixes #265
> Make nix build produce a static binary

- src/loader/loader.go
Why
===
* https://github.com/F1bonacc1/process-compose/issues/294
What changed
===
* Make a copy of the FileNames and loop over that instead, so when loadExtendProject adds to the FileNames, it doesn't try to load it again
Test plan
===
* The repro in issue 294 now passes
> fix: stop loading the same project multiple times 294

- src/cmd/up.go
6b9ce00 added `detached-with-tui` for the root command. This adds support to the up
> feat: up support detached-with-tui

- process-compose.yaml
- src/cmd/update.go
**Why?**
Enable loading/unloading processes by namespace.
This allows grouping processes under namespaces, making it easier to manage dependencies in different environments. For example:
- A **dev** namespace can be used to start only development dependencies.
- The **default** namespace can be used for full integration testing.
By supporting `--namespace`, users can update projects more granularly, starting/stopping only the required processes.
> feat: support namespace arg in project update command

- src/types/process.go
- Fix `IsRunning` (should be `is_running`) serialization on the process state, to be aligned with the other outputs.
> fix: wrong serialization on process state `IsRunning`

- src/app/table.go
- src/cmd/list.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/config/Flags.go
- src/tui/proc-table.go
- src/tui/tui_option.go
- src/tui/view.go
- src/types/process.go
- src/types/process_test.go
`process-compose --detached-with-tui --detach-on-success` will act like `--detached-with-tui`, but will automatically detach if and when all processes start up succesfully.
After detaching, a table showing the started processes is printed automatically.
Closes #311
> Add `--detach-on-success`

- src/pclog/logger_facade.go
These messages are not very useful and they clog up the logs:
$ cat .pc/logs/process-compose.log | rg flushing | wc -l
8940
> Don't log "flushing"

- .github/workflows/docs.yml
- www/mkdocs.yml
I noticed that the docs CI build for #326 failed with a permissions error:
```
INFO    -  Copying '/home/runner/work/process-compose/process-compose/www/site' to 'gh-pages' branch and pushing to GitHub.
remote: Permission to F1bonacc1/process-compose.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/F1bonacc1/process-compose/': The requested URL returned error: 403
```
We don't want to deploy the docs for PR CI runs, so let's run `mkdocs build` instead to make sure the docs build without deploying them.
I also updated the `mkdocs.yml` to fix this deprecation warning:
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' …
> GitHub Actions: Fix docs build in CI

- src/tui/view.go
Previously, attempting to shut down `process-compose` would incur a 1-second delay.
With #312, this meant that `process-compose --detached-with-tui --detach-on-success` would take longer than 1 second to return, even if the project was already running and healthy (and therefore the command should have been a no-op).
Removing this sleep makes that command take ~90ms instead of ~1050ms.
> Shutdown instantly

- default.nix
- go.mod
- go.sum
Bumps purego to fix a linker issue with dlopen on x86_64-darwin.
```
link: duplicated definition of symbol dlopen, from github.com/ebitengine/purego and github.com/ebitengine/purego
````
See https://github.com/ebitengine/purego/pull/312
Run the following on `main` to reproduce the error:
```
nix flake update
nix build
```
> fix: fix builds on x86_64-darwin

- src/app/proc_opts.go
- src/app/process.go
- src/app/project_opts.go
- src/app/project_runner.go
- src/cmd/project_runner.go
- src/cmd/root.go
- src/cmd/up.go
- src/config/Flags.go
- src/config/config.go
- www/docs/cli/process-compose.md
- www/docs/cli/process-compose_up.md
Most of the projects I am using process compose with have upwards of 10 processes. Having each instance of process compose take about 1 CPU just for management isn't scalable, alas, since I need to have 2 or 3 projects running concurrently for development. This PR makes optional being able to disable the accurate metrics gathering.
resolve #341
> feat: default to imprecise metrics and provide option to enable them

- src/tui/proc-table.go
At work, we use `--detach-on-success` (https://github.com/F1bonacc1/process-compose/pull/312) to automatically exit the `process-compose` TUI when processes finish starting up. When processes fail to start up, engineers often don't notice that a process has failed, and instead assume that `process-compose` has a bug.
The UI makes it pretty easy to miss a failed process; the icon on the left of the table is red, but that's about it. The exit code is off to the right, and it's not immediately obvious that a 1 means there's a problem.
We can make the UI significantly more legible by coloring rows according to the process state. We'll reuse the color of the state icon for this. This displays nicely when rows are selected as well; a selected failed process will show up with black text on a red …
> table: color rows according to proc status

- src/tui/proc-table.go
- src/types/process.go
Related: #339
When a process completes with a non-zero exit code, display "Failed" in the "Status" column instead of "Completed". "Completed" sounds like everything is OK, and "Failed" makes it clearer that something has gone wrong.
> table: display "Failed" for status

- fixtures-code/process-compose-shutdown-inorder.yaml
- src/app/project_runner.go
- src/app/system_test.go
This bug affects the shutdown order when multiple dependencies and the option  `--ordered-shutdow ` are used. This change fixes the `reverseDependencies` list to include all dependencies and the shutdown order then works smoothly with multiple dependencies.
> fix: reverse shutdown order does not contain all dependencies

- src/app/process.go
- src/command/stopper_windows.go
- Obey parentOnly for Windows and add same log as for Unix
- In case of shutdown timeout, per [docs](https://github.com/F1bonacc1/process-compose/blob/main/www/docs/launcher.md?plain=1#L176), the process group should receive the `SIGKILL` signal (irrespective of the `shutdown.parent_only` option)
> app, config: Obey parentOnly for Windows and add same log as for Unix and fix forceKillOnTimeout

- schemas/process-compose-schema.json
- shell.nix
- src/api/pc_api.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/types/process.go
- src/types/project.go
Next config is valid and runs well by latest process compose:
```json
{
"log_location": "/tmp/n1-services/nord-deps/pc.log",
"processes": {
"hist": {
"availability": {
"max_restarts": 5,
"restart": "on_failure"
},
"command": "/nix/store/vjbbbnj3pjqfxg25fln5na6pv581h4a9-start-postgres/bin/start-postgres",
"depends_on": {
"hist-init": {
"condition": "process_completed_successfully"
}
},
"namespace": "postgres.hist",
"readiness_probe": {
"exec": {
"command": "/nix/store/zzyl3swwn6flq975s025csl1mr3lqzq2-postgresql-and-plugins-17.5/bin/pg_isready -h 127.0.0.1 -p 5432 -d template1 -U postgres"
},
"failure_threshold": 5,
"initial_delay_seconds": 2,
"period_seconds": 10,
"success_threshold": 1,
"timeout_seconds": 4
},
"shutdown": {
"signal": 2
}
},
"hist-init": {
"command": …
```
> chore(schema): fixed process compose schema(based on realworld configs) and swagger API desync with code
